import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Box } from '@chakra-ui/react'
import Pricingheading from './Components/Heading'
import MainPriceContainer from './Components/PriceMainDisplay/boxcontainer'
import BottomIcons from './Components/BottomIcons'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >

        <Box width="100%" height="400px" bg="#6B46C1;
">
      <Pricingheading/>
      <MainPriceContainer/>
      <BottomIcons/>
        </Box>
             </main>
    </>
  )
}
